language: c
os: linux
dist:
    - bionic


addons:
    apt:
        update: true
        packages:
            - make
            - gcc
            - clang
            - qemu-user-static
            - wine-stable
            - wine32

# We use docker for the cross-build
services:
  - docker

# All our jobs
env:
    matrix:      
      - BLINDING=0 COMPLETE=0
      - BLINDING=1 COMPLETE=0
      - BLINDING=0 COMPLETE=1
      - BLINDING=1 COMPLETE=1
      - CC=clang BLINDING=0 COMPLETE=0
      - CC=clang BLINDING=1 COMPLETE=0
      - CC=clang BLINDING=0 COMPLETE=1
      - CC=clang BLINDING=1 COMPLETE=1

script:
       - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then git fetch github refs/pull/${TRAVIS_PULL_REQUEST}/head && git checkout FETCH_HEAD; fi
       - make && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make && cd - && make clean
       - make 16 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make 16 && cd - && make clean
       - make 32 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make 32 && cd - && make clean
       - make 64 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make 64 && cd - && make clean
       - make debug && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make debug && cd - && make clean
       - make debug16 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make debug16 && cd - && make clean
       - make debug32 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make debug32 && cd - && make clean
       - make debug64 && ./build/ec_self_tests vectors vectors && ./build/ec_self_tests vectors rand
       - cd src/examples/ && make clean && make debug64 && cd - && make clean
       # Cross build jobs
       - sh scripts/crossbuild.sh
       # Test generated cross binaries through qemu-static
       - sh scripts/crossrun.sh -cpu 1 
 
notifications:
  email:
    recipients:
      - ryadbenadjila@gmail.com
    on_success: never
    on_failure: always
    on_pull_requests: always
