name: libecc

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  runtime_tests:
    runs-on: ubuntu-latest
    strategy:
      #max-parallel: 10
      matrix:
        cc: [gcc, clang]
        blinding: [1]
        cryptofuzz: [1]
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # libecc runtime tests
      - name: libecc runtime tests
        env:
          CC: ${{ matrix.cc }}
          BLINDING: ${{ matrix.blinding }}
          CRYPTOFUZZ: ${{ matrix.cryptofuzz }}
          ASSERT_PRINT: 1
          # We want to parallelize self tests
          OPENMP_SELF_TESTS: 1
        shell: bash
        run: |
          # Vanilla tests
          #
          make && ./build/ec_self_tests vectors rand;
          make 32 && ./build/ec_self_tests vectors rand;
          make 16 && ./build/ec_self_tests vectors rand;
        continue-on-error: false
